### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by ogallagher** [ogallagher/graphics_final#2]
Investigate how to add sound effects and maybe a soundtrack to the game.
SFX:
- shot
- hit
- time speed-up
- time slow-down

**Comment by ogallagher** [comment]
[LearnOpenGL](https://learnopengl.com/In-Practice/2D-Game/Audio) uses [Irrklang](https://www.ambiera.com/irrklang/tutorials.html) as its sound library, which seems to have all the functionality we’d want. I’ve linked the site that uses it and the tutorials published by the makers of the library. It supports sound positioning (left/right/near/far), layered playback, and multiple OS’s.

**Comment by brianjypark** [comment]
Decided not to implement sound for now.
