### ISSUE TITLE
Enemy behaviour

### ISSUE THREAD

**Issue by ogallagher** [ogallagher/graphics_final#3]
- look toward the player
- spawn time
- movement (follow player, stand time, collision)
- reload time
- spawn location
- die on bullet hit

**Comment by ogallagher** [comment]
Look toward player is finished, as well as basic movement.

**Comment by ogallagher** [comment]
> - spawn location
> - die on bullet hit
> - spawn location

Working on these.

**Comment by brianjypark** [comment]
die on bullet hit updated
-Enemy bullet does not kill another enemy
Reload time + movement has getRandom() added

**Comment by ogallagher** [comment]
Enemy behavior has reached expectations.
