### ISSUE TITLE
Visuals

### ISSUE THREAD

**Issue by ogallagher** [ogallagher/graphics_final#8]
Make the visuals more sophisticated (complex objects in the scene, animations).
- Person: create legs, arms, and gun
- Person: animate walking
- Bullet: motion blur with small cube at the end (or some other primitive)
- Pick a consistent color scheme
- Light
- Material properties
    - obstacle
    - person
        - player
        - enemy
    - fog

**Comment by ogallagher** [comment]
I created limbs for Person, but still need to add in the gun and make the legs point according to Person.velocity.

**Comment by ogallagher** [comment]
Person’s legs now orient along its last nonzero velocity (`person-visuals`).

**Comment by ogallagher** [comment]
I animated Person’s legs to walk when moving, using World::speed (`person-visuals`).

**Comment by Gumichocopengin8** [comment]
@ogallagher  sounds great!

**Comment by ogallagher** [comment]
Working on adding light and obstacle material properties in `material-properties` branch.
I added the `help/blending_3d` example for reference.

**Comment by ogallagher** [comment]
All visuals done. Skipping fog and bullet blur visuals.
