### ISSUE TITLE
Name the game

### ISSUE THREAD

**Issue by ogallagher** [ogallagher/graphics_final#9]
Think of 5 to 10 names and we can pick one of them.

**Comment by ogallagher** [comment]
1. Faster
2. Quickfire
3. Shot Clock
4. Hot Second
5. Turnstyle
6. Revolver
7. Warp Gunner
8. Hold Fire
9. Open Fire
10. Minuteman

**Comment by brianjypark** [comment]
Game Name: Minuteman
